### ISSUE TITLE
优化一下上传docker镜像的workflow？

### ISSUE THREAD

**Issue by xiaozhikang0916** [jwcesign/kubespider#100]
现在在pr合入之后，上传docker的workflow基本都是失败的：[actions](https://github.com/jwcesign/kubespider/actions/workflows/kubespider-dockerhub-latest-build.yaml)，并且每次都在dockerhub上覆盖旧的镜像tag，较难随时更新版本使用，考虑优化一下上传的workflow？

**Comment by jwcesign** [comment]
失败的我周末修修，不知道为啥别人的PR获取不到secret。

> 并且每次都在dockerhub上覆盖旧的镜像tag，较难随时更新版本使用. 

这个我是这么设计的，master都是用latest(每次有新提交就覆盖latest tag)，每个release用对应的tag，比如v0.1.0, v0.2.0
`较难随时更新版本使用` 指什么？

**Comment by jwcesign** [comment]
应该可以解决：https://stackoverflow.com/questions/58737785/github-actions-empty-env-secrets

**Comment by jwcesign** [comment]
这个按正常的发布策略，main跑出来的就是latest，release-x构建的是各版本。当然latest不保证百分百稳定，后续可能需要把这个策略落实到安装手册里
