### ISSUE TITLE
feat: 通过自定义选择器支持资源网站

### ISSUE THREAD

**Issue by qingchoulove** [jwcesign/kubespider#115]
## Describe the background
现有模式，资源站（source_provider）依赖开发人员为每一个网站适配，成本较高。
是否有模式可以通过配置项支持有相同模式的资源站。

## Describe the feature
根据`source_provider.provider.SourceProvider`定义，需要实现`should_handle`和`get_links`两个关键方法。
阅读`MeijuttSourceProvider`代码，`get_links`其实是通过`BeautifulSoup`进行解析。
综上，是否可以通过`BeautifulSoup`的`select`支持的能力，通过用户配置`xpath`或`css selector`来支持不同资源站。
例如：
### mjtt
xpath: `/html/body/div[2]/div[6]/div/div/div[3]/div[1]/ul/li `
css selector:` body > div.warp > div.o_cn2 > div > div > div.tabs-list.current-tab > div.down_list > ul > li > input`
### dygod
xpath: `//*[@id="downlist"]/table/tbody/tr/td/a`
css selector: `#downlist > table > tbody > tr > td > a`

### 表达式确认
可以通过chrome devtool进行预选则，然后根据实际情况进行调整。
<img width="474" alt="image" src="https://user-images.githubusercontent.com/9648420/235108468-589c3d29-8bff-43de-8b25-32f5d32a9ff0.png">

### 附录
[css selector](https://developer.mozilla.org/zh-CN/docs/Web/CSS/CSS_Selectors)
[xpath](https://developer.mozilla.org/en-US/docs/Web/XPath)

**Comment by jwcesign** [comment]
我更喜欢xpath，可以直接复制粘贴。或者两种都支持。

但是可能需要考虑如下问题：
1.获取到最终链接，可能要多级链接访问，如：
page a：有一个电影列表。
page b: page a 电影列表的一个元素。
page c: page b下一个链接保护的内容，存在magnet链接。

2.每个元素，获取的地方，可能不一样，如page a里面获取title， page b里面获取文件类型，page c里面获取链接。设计api得考虑。

**Comment by qingchoulove** [comment]
多页面获取下载链接的方式如果通过配置实现可能会比较复杂，可能要通过图描述。可以尝试先实现一个简单的单页面元素定位支持部分资源站，然后再根据诉求进行后续迭代。

**Comment by qingchoulove** [comment]
#151
