### ISSUE TITLE
下载失败

### ISSUE THREAD

**Issue by heywalter** [jwcesign/kubespider#129]
## Ask your question here:
**环境信息**：在宿主机上挂载了一个 NFS 文件夹，其目录为 /root/kubespider/nas，然后安装该工具，登录aira 的容器，可以正常创建文件和读取已有文件，担心和这个 NFS 挂载有关所以特意说明
下载时提示错误，容器输出的日志信息：
05/06 23:08:19 [NOTICE] Serialized session to '/config/aria2.session' successfully.
[#d8fb97 56KiB/56KiB(100%) CN:5 SD:1]
05/06 23:08:20 [NOTICE] Download complete: [MEMORY][METADATA]梅菲尔女巫.Mayfair.Witches.S01E01.The.Witching.Hour.1080p.H265-NEW字幕组.mp4
05/06 23:08:20 [NOTICE] Saved metadata as /downloads/57c7d3f11ac1c98cc9ef52a3ccf5091e14b97854.torrent.
05/06 23:08:20 [NOTICE] Serialized session to '/config/aria2.session' successfully.
05/06 23:08:20 [ERROR] CUID#86 - Exception caught while allocating file space.
Exception: [AbstractDiskWriter.cc:557] errNum=95 errorCode=17 fallocate failed. cause: Operation not supported
05/06 23:08:20 [ERROR] CUID#86 - Download not complete: /downloads/梅菲尔女巫.Mayfair.Witches.S01E01.The.Witching.Hour.1080p.H265-NEW字幕组.mp4
05/06 23:08:20 [NOTICE] Download GID#6d32f38fc9378fd2 not complete: /downloads/梅菲尔女巫.Mayfair.Witches.S01E01.The.Witching.Hour.1080p.H265-NEW字幕组.mp4
05/06 23:08:20 [WARRING] Number of files is zero, maybe a Magnet Link.
05/06 23:08:20 [INFO] Download task error, deleting files...
removed '/downloads/梅菲尔女巫.Mayfair.Witches.S01E01.The.Witching.Hour.1080p.H265-NEW字幕组.mp4.aria2'
removed '/downloads/梅菲尔女巫.Mayfair.Witches.S01E01.The.Witching.Hour.1080p.H265-NEW字幕组.mp4'
05/06 23:08:20 [INFO] Deleting .torrent file ...
removed '/downloads/57c7d3f11ac1c98cc9ef52a3ccf5091e14b97854.torrent'
05/06 23:08:20 [INFO] Deleting empty directory ...

用的就是[示例中的资源](https://www.meijutt.tv/content/meiju28044.html)

请问我应该如何排查，谢谢。

**Comment by jwcesign** [comment]
hello, @heywalter 感谢使用

不通过Kubespider，直接通过aria2的客户端，能正常下载吗？

**Comment by heywalter** [comment]
> 

非常感谢回复，这种方法尝试过也不行哦，在下载的过程中不停执行 ls 命令查看 下载目录，没有发现数据写入或新文件创建，这个比较奇怪

**Comment by jwcesign** [comment]
看起来是这个问题，https://github.com/aria2/aria2/issues/1032

**Comment by jwcesign** [comment]
这个估计是arai2那边启动参数要设置下，如果你有时间也可以修修；
暂时的规避办法，可以不用nfs文件系统

**Comment by heywalter** [comment]
感谢指点，修改参数并重启镜像后问题已解决（看了配置文件我也是固态硬盘，这样配置寿命也好一些），感谢大佬非常酷的工具。Btw，抱歉不太会代码哦，如果需要文档资料的输出我可以贡献的（我是一名文档工程师）

**Comment by jwcesign** [comment]
hello @heywalter  可以搞一个FAQ.md吗？  把这个问题记录一下？

**Comment by heywalter** [comment]
> hello @heywalter 可以搞一个FAQ.md吗？ 把这个问题记录一下？

好滴我记着啦，最快下周完成
