### ISSUE TITLE
feat: Support configuration reload automatically after changed

### ISSUE THREAD

**Issue by jwcesign** [jwcesign/kubespider#142]
## Describe the background

Now after the configuration is changed, users need to restart the kubespider container, and it's a redundant step.

## Describe the feature

* Support configuration reload automatically after changed, and do not need to restart the kubespider container.

**Comment by ijwstl** [comment]
> cc @ijwstl @xiaozhikang0916 两位大佬这个有时间搞搞吗？
这个貌似加个文件监控，检测到文件变化直接重启kubespider即可吧，我明天看看

**Comment by xiaozhikang0916** [comment]
可以考虑main函数作为守护进程，在子进程中调用`kubespider.run()`，在需要重启的时候由守护进程kill再重启
