### ISSUE TITLE
配置使用

### ISSUE THREAD

**Issue by wangjiyun** [jwcesign/kubespider#36]
配置怎么改  ,   运行脚本如下提示:

Unable to find image 'cesign/aria2-pro:latest' locally
docker: Error response from daemon: Get "https://registry-1.docker.io/v2/": net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers).
See 'docker run --help'.
[root@localhost kubespider]# ls

**Comment by ultraji** [comment]
看着是网络不通，尝试通过`docker pull cesign/aria2-pro:latest`手动拉取镜像试一下

**Comment by jwcesign** [comment]
谢谢使用，可以使用试试
```sh
export CHINA_MAINLAND=TRUE
bash hack/install_kubespider.sh
```

**Comment by jwcesign** [comment]
@wangjiyun 怎么样？
