### ISSUE TITLE
mikanani资源提供器配置无法正常下载

### ISSUE THREAD

**Issue by protonXyz** [jwcesign/kubespider#40]
请教一下，通过浏览器插件发送到配置里的美剧可以正常添加到aria2中并下载操作，但直接将配置文件中的mikanani启动并替换为自己的rss后，再重启容器，aria2无法接受到任何mikanani的下载项，还有有日志文件吗？如果发送异常了怎么排错？
![image](https://user-images.githubusercontent.com/117502780/218666098-3d220e9a-c75c-46d2-8877-9a53cdae29ac.png)

**Comment by jwcesign** [comment]
hello，谢谢使用！

这个你直接访问rss链接会有类容吗（curl一下）？ mikanani好像只会显示最近2/3天的更新类容。

**Comment by jwcesign** [comment]
可以把docker logs kubespider的内容贴一下吗？

**Comment by protonXyz** [comment]
抱歉，可能是我这里的网络问题？我今天尝试的时候
![image](https://user-images.githubusercontent.com/117502780/219596816-0ae61d4f-78c6-4b9b-8765-79131bc5b475.png)
一开始仍然只能下载通过浏览器插件传递的美剧
![image](https://user-images.githubusercontent.com/117502780/219597022-3ccdb7f0-32a5-49a6-b526-0c6bfadb0d55.png)
查看日志也没有问题，就是aria2上只有美剧
![image](https://user-images.githubusercontent.com/117502780/219597278-0c35cab7-d4d5-4f9c-b21c-5f735a4f4a23.png)
最后我把容器，镜像都删除了重装了一下就正常了😅

**Comment by jwcesign** [comment]
有兴趣来开发开发吗？这边还有很多特性，哈哈
