### ISSUE TITLE
我这个报错怎么搞

### ISSUE THREAD

**Issue by mtyzaq** [jwcesign/kubespider#44]
20 18:15:22,705-INFO: Get webhook trigger:magnet:?xt=urn:btih:4ba1e93b9f4680e2e91df56d7e4a3b4292de5fcc&dn=[%E7%94%B5%E5%BD%B1%E5%A4%A9%E5%A0%82www.dytt89.com]%E8%9A%81%E4%BA%BA%E4%B8%8E%E9%BB%84%E8%9C%82%E5%A5%B3%EF%BC%9A%E9%87%8F%E5%AD%90%E7%8B%82%E6%BD%AE-2023_HDTC%E4%B8%AD%E8%8B%B1%E5%8F%8C%E5%AD%97.mp4&tr=http://t.t789.me:2710/announce&tr=http://t.t789.co:2710/announce&tr=http://t.t789.vip:2710/announce
20 18:15:22,705-INFO: Download mangent file
20 18:15:22,706-INFO: Start magnet download:magnet:?xt=urn:btih:4ba1e93b9f4680e2e91df56d7e4a3b4292de5fcc&dn=[%E7%94%B5%E5%BD%B1%E5%A4%A9%E5%A0%82www.dytt89.com]%E8%9A%81%E4%BA%BA%E4%B8%8E%E9%BB%84%E8%9C%82%E5%A5%B3%EF%BC%9A%E9%87%8F%E5%AD%90%E7%8B%82%E6%BD%AE-2023_HDTC%E4%B8%AD%E8%8B%B1%E5%8F%8C%E5%AD%97.mp4&tr=http://t.t789.me:2710/announce&tr=http://t.t789.co:2710/announce&tr=http://t.t789.vip:2710/announce
20 18:15:24,513-WARNING: Please ensure your motrix server is ok:Unauthorized

用的迅雷3.4.0

**Comment by jwcesign** [comment]
你用的迅雷作为下载软件吗？

**Comment by jwcesign** [comment]
日志看起来你还是用的 aria2 下载器

**Comment by jwcesign** [comment]
想用迅雷请参考：https://github.com/jwcesign/kubespider/blob/main/docs/zh/user_guide/thunder_install_config/README.md

**Comment by jwcesign** [comment]
同学能麻烦提个PR吗，日志里面：
```
20 18:15:24,513-WARNING: Please ensure your motrix server is ok:Unauthorized
```
应该为:
```
20 18:15:24,513-WARNING: Please ensure your aria2 server is ok:Unauthorized
```

**Comment by mtyzaq** [comment]
搞好了。容器配置文件路径映射错了

**Comment by jwcesign** [comment]
同学能来个PR吗？

**Comment by jwcesign** [comment]
可以问下你是用的迅雷吗？

**Comment by mtyzaq** [comment]
是的

**Comment by jwcesign** [comment]
所以同学来个PR吧😆？修复一下那个日志？

**Comment by mtyzaq** [comment]
PR是啥？
20 18:32:43,251-INFO: Source Provider:btbtt12_disposable_source_provider enabled...
20 18:32:43,251-INFO: Source Provider:meijutt_source_provider enabled...
20 18:32:43,252-INFO: Download Provider:xunlei_download_provider enabled...
20 18:32:43,252-INFO: Period Server start running...
20 18:32:43,253-INFO: meijutt tv link is:
20 18:32:43,253-INFO: Webhook Server start running...
20 18:33:04,414-INFO: Get webhook trigger:magnet:?xt=urn:btih:4ba1e93b9f4680e2e91df56d7e4a3b4292de5fcc&dn=[%E7%94%B5%E5%BD%B1%E5%A4%A9%E5%A0%82www.dytt89.com]%E8%9A%81%E4%BA%BA%E4%B8%8E%E9%BB%84%E8%9C%82%E5%A5%B3%EF%BC%9A%E9%87%8F%E5%AD%90%E7%8B%82%E6%BD%AE-2023_HDTC%E4%B8%AD%E8%8B%B1%E5%8F%8C%E5%AD%97.mp4&tr=http://t.t789.me:2710/announce&tr=http://t.t789.co:2710/announce&tr=http://t.t789.vip:2710/announce
20 18:33:04,414-INFO: Download mangent file
20 18:33:04,415-INFO: Start magnet download:magnet:?xt=urn:btih:4ba1e93b9f4680e2e91df56d7e4a3b4292de5fcc&dn=[%E7%94%B5%E5%BD%B1%E5%A4%A9%E5%A0%82www.dytt89.com]%E8%9A%81%E4%BA%BA%E4%B8%8E%E9%BB%84%E8%9C%82%E5%A5%B3%EF%BC%9A%E9%87%8F%E5%AD%90%E7%8B%82%E6%BD%AE-2023_HDTC%E4%B8%AD%E8%8B%B1%E5%8F%8C%E5%AD%97.mp4&tr=http://t.t789.me:2710/announce&tr=http://t.t789.co:2710/announce&tr=http://t.t789.vip:2710/announce
20 18:33:04,570-INFO: Get xunlei token:1676889184.e1027d2cfbc2fc59a9c61de1c379f7e
11.98 - - [20/Feb/2023 18:33:04] "POST / HTTP/1.1" 200 -

这是我的日志

**Comment by jwcesign** [comment]
提个 
![image](https://user-images.githubusercontent.com/19745536/220086878-32e5f328-84f9-477a-8ada-b4cc67a39914.png)
 修复一下 https://github.com/jwcesign/kubespider/issues/44#issuecomment-1436726071

**Comment by jwcesign** [comment]
欢迎下次再来贡献代码！
