### ISSUE TITLE
如何发送种子文件？

### ISSUE THREAD

**Issue by miRemid** [jwcesign/kubespider#56]
从README的过程和个人使用情况来看，只能通过浏览器插件来发送URL形式的文件链接或种子链接给后端，如何发送文件形式的种子文件呢？

**Comment by jwcesign** [comment]
目前还不行，
这个直接打开aria2，把文件贴上去就行

**Comment by miRemid** [comment]
所以在Provider中里面的添加文件任务目前是无法使用的，我可以这么认为吗？
```python
@abc.abstractmethod
    def send_torrent_task(self, torrent_file_path, download_path):
        pass
```

**Comment by jwcesign** [comment]
这个你发送torrent文件链接，kubespider会下载torrent文件，然后把文件地址作为入参调用这个函数

**Comment by jwcesign** [comment]
> 所以在Provider中里面的添加文件任务目前是无法使用的，我可以这么认为吗？
> ```python
> @abc.abstractmethod
> def send_torrent_task(self, torrent_file_path, download_path):
>         pass
> ```

这个你看看对接aria2的函数实现就明白了

**Comment by jwcesign** [comment]
可以问下你是想实现什么吗？

**Comment by miRemid** [comment]
我现在正把qbittorrent放进去，由于qbittorrent只能下载种子文件或磁力链接不能下载普通的文件，所以我在想怎么利用`send_torrent_task`和`send_general_task`这俩接口

**Comment by jwcesign** [comment]
> 我现在正把qbittorrent放进去，由于qbittorrent只能下载种子文件或磁力链接不能下载普通的文件，所以我在想怎么利用`send_torrent_task`和`send_general_task`这俩接口

可以加下开发者讨论群，后面交流方便点
